# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "object-store-custom-http-external-crypto"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[features]
custom-http = []
custom-crypto = []
default = ["custom-http", "custom-crypto"]

[dependencies]
object_store = { path = "../../..", default-features = false, features = ["aws-base", "azure-base", "gcp-base", "http-base"] }
tokio = { version = "1", features = ["macros", "rt"] }
async-trait = "0.1"
http = "1"
http-body-util = "0.1"
sha2 = "0.10"
hmac = "0.12"
